"""
src/rule_engine.py
NGFW - Automated Rule Engine

Generates real iptables/pfSense-compatible firewall rules based on
ML classifications. Simulates automated threat response.

Author: Allben Rakgoale
"""

import pandas as pd
from datetime import datetime


class RuleEngine:
    """
    Converts ML predictions into firewall rules.

    Supports:
      - iptables syntax (Linux)
      - pfSense syntax (BSD/FreeBSD)
    """

    # Threshold for auto-blocking
    BLOCK_THRESHOLD = 0.80

    # Attack types that should always be blocked
    BLOCKABLE_ATTACKS = {"port_scan", "ddos", "exfiltration"}

    def __init__(self):
        self.blocked_ips = set()
        self.rules = []
        self.chain_counter = 1

    # -----------------------------------------------------
    # Rule Generation
    # -----------------------------------------------------
    def generate_rules(
        self,
        scored_df: pd.DataFrame,
        format: str = "iptables",
    ) -> pd.DataFrame:
        """
        Generate firewall rules from scored traffic flows.

        Args:
            scored_df: DataFrame with predicted_label + confidence
            format: 'iptables' or 'pfsense'

        Returns:
            DataFrame of generated rules
        """
        # Filter to malicious flows above confidence threshold
        malicious = scored_df[
            (scored_df["predicted_label"].isin(self.BLOCKABLE_ATTACKS)) &
            (scored_df["confidence"] >= self.BLOCK_THRESHOLD)
        ].copy()

        # Deduplicate by source IP (block once, not 100 times)
        unique_threats = malicious.drop_duplicates(subset=["src_ip"])

        rules = []
        for _, row in unique_threats.iterrows():
            src_ip = row["src_ip"]
            attack = row["predicted_label"]
            confidence = row["confidence"]

            if format == "iptables":
                rule = (
                    f"iptables -A INPUT -s {src_ip} -j DROP "
                    f"# {attack.upper()} | conf={confidence:.2f}"
                )
            elif format == "pfsense":
                rule = (
                    f"block drop in quick on em0 from {src_ip} to any "
                    f"# {attack.upper()} | conf={confidence:.2f}"
                )
            else:
                raise ValueError(f"Unsupported format: {format}")

            rules.append({
                "rule_id": f"R{self.chain_counter:04d}",
                "src_ip": src_ip,
                "attack_type": attack,
                "confidence": confidence,
                "rule": rule,
                "created_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            })
            self.chain_counter += 1
            self.blocked_ips.add(src_ip)

        rules_df = pd.DataFrame(rules)
        self.rules.extend(rules)
        return rules_df

    # -----------------------------------------------------
    # Summary
    # -----------------------------------------------------
    def get_summary(self) -> dict:
        """Return summary of blocked threats."""
        if not self.rules:
            return {"total_blocked": 0, "by_attack": {}}

        rules_df = pd.DataFrame(self.rules)
        return {
            "total_blocked": len(self.blocked_ips),
            "by_attack": rules_df["attack_type"].value_counts().to_dict(),
            "average_confidence": round(rules_df["confidence"].mean(), 3),
        }

    # -----------------------------------------------------
    # Export
    # -----------------------------------------------------
    def export_iptables_script(self) -> str:
        """Export rules as a runnable bash script."""
        header = """#!/bin/bash
# =====================================================
# NGFW Auto-Generated Firewall Rules
# Generated by: allben-ngfw-ml-firewall
# Author: Allben Rakgoale
# =====================================================

# Flush existing rules (CAUTION: use only in test environments)
# iptables -F

# Auto-block rules:
"""
        rules_block = "\n".join([r["rule"] for r in self.rules]) if self.rules else "# No rules generated"

        footer = """

# =====================================================
# Rule summary:
"""
        summary = self.get_summary()
        footer += f"# Total blocked IPs: {summary['total_blocked']}\n"
        footer += f"# Average confidence: {summary.get('average_confidence', 0)}\n"

        return header + rules_block + footer

    def export_pfsense_script(self) -> str:
        """Export rules as pfSense-compatible format."""
        header = """# =====================================================
# NGFW Auto-Generated pfSense Rules
# Generated by: allben-ngfw-ml-firewall
# Author: Allben Rakgoale
# =====================================================
# Format: block drop in quick on <interface> from <IP> to any
# =====================================================

"""
        rules_block = "\n".join([
            r["rule"].replace("iptables -A INPUT -s ", "block drop in quick on em0 from ")
            .split("#")[0].strip() + " to any # " + r["rule"].split("#")[1].strip()
            for r in self.rules
        ]) if self.rules else "# No rules generated"

        return header + rules_block


if __name__ == "__main__":
    from traffic_simulator import generate_traffic
    from classifier import TrafficClassifier

    print("🌐 Generating traffic...")
    df = generate_traffic(n_flows=500)

    print("🤖 Training classifier...")
    classifier = TrafficClassifier()
    metrics = classifier.train(df)
    print(f"✅ Accuracy: {metrics['accuracy']}")

    print("\n🔍 Predicting on all flows...")
    scored = classifier.predict(df)

    print("\n🛡️  Generating firewall rules...")
    engine = RuleEngine()
    rules = engine.generate_rules(scored, format="iptables")
    print(f"✅ Generated {len(rules)} rules")

    if not rules.empty:
        print("\n📋 Sample rules:")
        print(rules[["rule_id", "src_ip", "attack_type", "rule"]].head().to_string(index=False))
